### ISSUE TITLE
version on npm

### ISSUE THREAD

**Issue by janusch** [broucz/react-inline-grid#1]
Hey,
i'd love to try out your package, was wondering if you could publish 0.3.0 to npm? Latest on npm is 2.1. if i am not mistaken?

Keep up the great work!

**Comment by broucz** [comment]
Hi,
my mistake sorry, thank you for reporting this.
I just published it and you'll be able to use `v0.3.0` from npm.

FYI, `v.0.4.0` will be release from tomorrow as I'll update `options` shape => removing need of `{ bigger: true }`.

Also, the `options` shape present in the `README.md` file is for `v0.2.1`.
Please check https://github.com/broucz/react-inline-grid/releases/tag/v0.3.0 or https://github.com/broucz/react-inline-grid/blob/master/src/constants.js for reference.

Thanks for the support, and any feedback is more than welcome !
