### ISSUE TITLE
React-Router history navigation fails

### ISSUE THREAD

**Issue by gregziegan** [broucz/react-inline-grid#3]
When navigating back in the browser history, all routes using react-inline-grid in my application cause the navigation to fail. The URL will change but the components fail to be swapped out due to the error in the function `unsubscribe`.

``` javascript
Uncaught TypeError: Cannot read property 'indexOf' of undefined
unsubscribe @ matchMedia.js:91
```

Currently using the most up-to-date versions of _react-router_, _react_, and the _history_ libraries. _react-router_ (1.0.0-rc1) and _react_ (0.14.0-rc1). This may have more to do with the _history_ module (currently using version 1.9.0).

**Comment by JadenH** [comment]
Hi @thebritican,

I just started using this package today and ran into this same issue. 

I tracked down the issue to this function in matchMedia.js.

``` javascript
    return function unsubscribe() {
      var index = this.listeners.indexOf(listener);
      this.listeners = this.listeners.slice(index, 1);
    };
```

I added a check to see if this.listeners is null and it seemed to correct the issue. Can't be sure that it will cause other issues, but testing I haven't found any problems.

``` javascript
    return function unsubscribe() {
      if(this.listeners != null) {
        var index = this.listeners.indexOf(listener);
        this.listeners = this.listeners.slice(index, 1);
      }
    };
```

**Comment by broucz** [comment]
Hi guys !
First of all @thebritican I'm sorry for the late reply... 

:pray: Thanks for the report and @JadenH PR.

I missed time this month to work on this repo, but I'll be able to work on it during the first week of November. Many things have to be rework, specially concerning state management and media updates. I'll keep you updated.

**Comment by JadenH** [comment]
Hi @broucz,

Any updates coming down the pipeline soon? Could you look at my submitted pull request as a possible (even temporary) solution to resolve this issue?

Thanks,
Jaden
