### ISSUE TITLE
Usage within redux overwrite my app state

### ISSUE THREAD

**Issue by igoldny** [broucz/react-inline-grid#6]
i'm writing redux app and if i wrap my app with Grid its overwrite my state and i get  react-inline-grid state within my app

**Comment by kartikag01** [comment]
i have used https://github.com/dowjones/react-cellblock it doesn't have overwrite state issue

**Comment by micahthomas** [comment]
Yeah seriously threw me for a loop, atleast put some disclaimer on the README

**Comment by sdee** [comment]
Is there a workaround for this issue? 

I posted a question on Stackoverflow (http://stackoverflow.com/questions/43927596/components-loose-access-to-store-when-wrapped-in-grid-react-inline-grid/) and someone directed me here.

Seems like the Grid's component provider is overwriting my App's provider.

**Comment by micahthomas** [comment]
I don't think there is a easy workaround. You would need to pass in the store via another provider component or via props.

I ended up switching to [react-flexbox-grid](https://roylee0704.github.io/react-flexbox-grid/), it took some work but ended up being a simpler and reliable solution.
